export const phoneCountryOptions = [
  { iso: "IN", code: "+91", label: "India (+91)" },
  { iso: "AE", code: "+971", label: "UAE (+971)" },
  { iso: "US", code: "+1", label: "United States (+1)" },
  { iso: "GB", code: "+44", label: "United Kingdom (+44)" },
  { iso: "CA", code: "+1", label: "Canada (+1)" },
  { iso: "AU", code: "+61", label: "Australia (+61)" },
  { iso: "DE", code: "+49", label: "Germany (+49)" },
  { iso: "FR", code: "+33", label: "France (+33)" },
  { iso: "ES", code: "+34", label: "Spain (+34)" },
  { iso: "IT", code: "+39", label: "Italy (+39)" },
  { iso: "NL", code: "+31", label: "Netherlands (+31)" },
  { iso: "SE", code: "+46", label: "Sweden (+46)" },
  { iso: "NO", code: "+47", label: "Norway (+47)" },
  { iso: "DK", code: "+45", label: "Denmark (+45)" },
  { iso: "FI", code: "+358", label: "Finland (+358)" },
  { iso: "SG", code: "+65", label: "Singapore (+65)" },
  { iso: "MY", code: "+60", label: "Malaysia (+60)" },
  { iso: "PH", code: "+63", label: "Philippines (+63)" },
  { iso: "ID", code: "+62", label: "Indonesia (+62)" },
  { iso: "JP", code: "+81", label: "Japan (+81)" },
  { iso: "KR", code: "+82", label: "South Korea (+82)" },
  { iso: "CN", code: "+86", label: "China (+86)" },
  { iso: "BR", code: "+55", label: "Brazil (+55)" },
  { iso: "AR", code: "+54", label: "Argentina (+54)" },
  { iso: "MX", code: "+52", label: "Mexico (+52)" },
  { iso: "ZA", code: "+27", label: "South Africa (+27)" },
  { iso: "NZ", code: "+64", label: "New Zealand (+64)" },
  { iso: "IE", code: "+353", label: "Ireland (+353)" },
  { iso: "BE", code: "+32", label: "Belgium (+32)" },
  { iso: "CH", code: "+41", label: "Switzerland (+41)" },
  { iso: "AT", code: "+43", label: "Austria (+43)" },
  { iso: "PT", code: "+351", label: "Portugal (+351)" },
  { iso: "GR", code: "+30", label: "Greece (+30)" },
  { iso: "TR", code: "+90", label: "Turkey (+90)" },
  { iso: "SA", code: "+966", label: "Saudi Arabia (+966)" },
  { iso: "KW", code: "+965", label: "Kuwait (+965)" },
  { iso: "QA", code: "+974", label: "Qatar (+974)" },
  { iso: "OM", code: "+968", label: "Oman (+968)" },
  { iso: "BH", code: "+973", label: "Bahrain (+973)" },
  { iso: "EG", code: "+20", label: "Egypt (+20)" },
  { iso: "NG", code: "+234", label: "Nigeria (+234)" },
  { iso: "KE", code: "+254", label: "Kenya (+254)" },
  { iso: "TZ", code: "+255", label: "Tanzania (+255)" },
  { iso: "UG", code: "+256", label: "Uganda (+256)" },
  { iso: "VN", code: "+84", label: "Vietnam (+84)" },
  { iso: "TH", code: "+66", label: "Thailand (+66)" },
  { iso: "PK", code: "+92", label: "Pakistan (+92)" },
  { iso: "BD", code: "+880", label: "Bangladesh (+880)" },
  { iso: "LK", code: "+94", label: "Sri Lanka (+94)" },
  { iso: "NP", code: "+977", label: "Nepal (+977)" },
  { iso: "MM", code: "+95", label: "Myanmar (+95)" },
  { iso: "IL", code: "+972", label: "Israel (+972)" },
  { iso: "RU", code: "+7", label: "Russia (+7)" },
  { iso: "PL", code: "+48", label: "Poland (+48)" },
  { iso: "CZ", code: "+420", label: "Czech Republic (+420)" },
  { iso: "HU", code: "+36", label: "Hungary (+36)" },
  { iso: "RO", code: "+40", label: "Romania (+40)" },
  { iso: "BG", code: "+359", label: "Bulgaria (+359)" },
  { iso: "UA", code: "+380", label: "Ukraine (+380)" },
  { iso: "BY", code: "+375", label: "Belarus (+375)" },
  { iso: "KZ", code: "+7", label: "Kazakhstan (+7)" },
  { iso: "AZ", code: "+994", label: "Azerbaijan (+994)" },
  { iso: "GE", code: "+995", label: "Georgia (+995)" },
] as const;

export type PhoneCountryOption = (typeof phoneCountryOptions)[number];

export default phoneCountryOptions;
