name: Deploy Admin Portal

on:
  push:
    branches:
      - main
    paths:
      - "apps/admin-portal/**"
      - ".github/workflows/deploy-admin-portal.yml"
      - ".github/workflows/vercel-deploy-reusable.yml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/vercel-deploy-reusable.yml
    with:
      app_name: admin-portal
      app_path: apps/admin-portal
    secrets:
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_ADMIN_PORTAL }}
